version: "2.3"
services:
  db:
    image: mysql:latest
    volumes:
      - type: bind
        source: ./database
        target: /docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=twitterlight
      - MYSQL_USER=user
      - MYSQL_PASSWORD=admin
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined
  web:
    image: twitterlight/twitterlight
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=twitterlight
      - DATABASE_PORT=3306